version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: node:12.13.1

    working_directory: client/

    steps:
      - checkout

      - run: npm install

      - run: npm run build

      - run: npm run start:dev
